baseURL = "https://smartsilicium.github.io/SmartSilicium/"
languageCode = "fr-fr"
title = "SmartSilicium"
theme = "PaperMod"

[params]
    defaultTheme = "auto" # Active le mode sombre automatique
    description = "Hardware, Code & Tech"
    
    # Ton logo (Texte + Emoji)
    label.text = "SmartSilicium"
    label.icon = "ðŸ’¾" 

    # Les rÃ©seaux sociaux (s'afficheront en haut)
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/SmartSilicium"

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Accueil"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "hardware"
        name = "Hardware"
        url = "/categories/hardware/"
        weight = 2

    [[menu.main]]
        identifier = "software"
        name = "Logiciels"
        url = "/categories/logiciels/"
        weight = 3

    [[menu.main]]
        identifier = "about"
        name = "Ã€ Propos"
        url = "/about/"
        weight = 4