# Nom du robot
name: Deploy Hugo site to Pages

on:
  # Se déclenche quand tu pushes sur la branche main
  push:
    branches:
      - main
  # Permet de lancer manuellement si besoin
  workflow_dispatch:

# Permissions pour que GitHub puisse écrire sur ton site
permissions:
  contents: read
  pages: write
  id-token: write

# Une seule tâche de déploiement
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Tâche de construction
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # Important pour le thème Stack !

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true # Important pour le thème Stack !

      - name: Build
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Tâche de mise en ligne
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4